-- schema.sql
-- Создание таблицы mpa_rating (должна быть создана первой из-за внешних ключей)
CREATE TABLE IF NOT EXISTS mpa_rating
(
    id       INTEGER PRIMARY KEY,
    mpa_name VARCHAR(10)
    );

-- Создание таблицы users
CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    login    VARCHAR(255) NOT NULL,
    name     VARCHAR(255),
    birthday DATE         NOT NULL
    );

-- Создание таблицы genres
CREATE TABLE IF NOT EXISTS genres
(
    id         INTEGER PRIMARY KEY,
    genre_name VARCHAR(255) NOT NULL
    );

-- Создание таблицы films
CREATE TABLE IF NOT EXISTS films
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    releaseDate DATE         NOT NULL,
    duration    INTEGER      NOT NULL,
    mpa_id      INTEGER      REFERENCES mpa_rating (id) ON DELETE SET NULL
    );

-- Создание таблицы film_genres (связь многие-ко-многим между films и genres)
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  INTEGER NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genres (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

-- Создание таблицы friendship (дружба между пользователями)
CREATE TABLE IF NOT EXISTS friendship
(
    user_id   INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
    );

-- Создание таблицы likes (лайки фильмов пользователями)
CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

-- Создание индексов для ускорения поиска
CREATE INDEX IF NOT EXISTS idx_films_mpa_id ON films (mpa_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_film_id ON film_genres (film_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_genre_id ON film_genres (genre_id);
CREATE INDEX IF NOT EXISTS idx_friendship_user_id ON friendship (user_id);
CREATE INDEX IF NOT EXISTS idx_friendship_friend_id ON friendship (friend_id);
CREATE INDEX IF NOT EXISTS idx_likes_film_id ON likes (film_id);
CREATE INDEX IF NOT EXISTS idx_likes_user_id ON likes (user_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);